front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

front_homepage:
    pattern: /
    defaults: { _controller: FrontBundle:Main:index }
    requirements:
        _method: GET